import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header"

import type { Metadata } from "next";
import { alegreya, alegreyaSansSC, geistSans, geistMono } from "@/lib/fonts";
import "@/lib/styles/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={alegreya.variable} suppressHydrationWarning>
      <script
        async
        crossOrigin="anonymous"
        src="https://tweakcn.com/live-preview.min.js"
      ></script>
      <body className={`${alegreyaSansSC.variable}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
