on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        with:
          runs: bunx @11ty/exec
      
      - name: deploy2nekoweb
        uses: indiefellas/deploy2nekoweb@main
        with: 
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-domain: 'bravegrumpy.nekoweb.org'
          nekoweb-username: 'bravegrumpy'
          directory: 'dist'